### PR TITLE
add: async sign offline

### PR DESCRIPTION
**Pull request by MioYvo**

### CODE REVIEW

**Comment by MioYvo** [comment]
knock knock

**Comment by andelf** [comment]
```
FAILED tests/test_client.py::test_client_sign_offline - AttributeError: type object 'Transaction' has no attribute 'from_json'
FAILED tests/test_client.py::test_async_client_sign_offline - AttributeError: type object 'AsyncTransaction' has no attribute 'from_json'
FAILED tests/test_client.py::test_client_update_tx - AttributeError: 'Transaction' object has no attribute 'update'
FAILED tests/test_contract.py::test_trc20_transfer - eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes
FAILED tests/test_contract.py::test_async_trc20_transfer - eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes
```

**Comment by MioYvo** [comment]
I test `tests/` folder locally it show all 'passed', please recheck this failed tests

**Comment by MioYvo** [comment]
FAILED tests/test_contract.py::test_trc20_transfer - eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes
FAILED tests/test_contract.py::test_async_trc20_transfer - eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

Due to test account(nile) `TGQgfK497YXmjdgvun9Bg5Zu3xE15v17cu`'s TRX balance is almost 0, i transfer 5000 trx to it, it shall not be failed again.

**Pull request merged**
