### PR TITLE
feat: sign_offline

### PR DESCRIPTION
**Pull request by MioYvo**
Make Transaction object locally without requests.

### CODE REVIEW

**Review by andelf — APPROVED** [review]

**Comment by andelf** [comment]
How about `def sign(self, priv_key=..,  verify_sign_weight=True):`?

**Comment by MioYvo** [comment]
> How about `def sign(self, priv_key=.., verify_sign_weight=True):`?

I think `sign_weight` is a must-have check, is not?

**Comment by andelf** [comment]
Making a Transaction object locally without requests is almost impossible for plain HTTP API.

Protobuf is needed.

**Comment by MioYvo** [comment]
sorry, I don't get the `Protobuf` point.

Now we can ship the Transaction object use it's `to_json()` func between systems and services, but we cannot rebuild a Transaction object from "json" object(dict or str) without requests to tron network (maybe a private tron node).

For example, there are two microservices: business_srv and tron_srv, 
1. business_srv call tron_srv.build_tx, and retain tx_json(tron_srv.build_tx using `tx.to_json`)
2. business_srv got tx_json, record it, build a Transaction object from it
3. business_srv sign Transaction object locally using tronpy
4. business_srv call tron_srv.submit_tx to submit this tx to tron network
5. if submit failed (maybe timeout or other exceptions) business_srv will call tron_srv.get_trancation_info to query this tx to make a confirm, even to re-send tx or other process. 

With this feature, business_srv will not require a connection to tron network, just use tronpy locally, will simplify the private tron node management and microservices deployment.

**Comment by andelf** [comment]
`sign_weight` is a trick used in tronpy. Actually, it is used to get the `txID` without calling the actual transaction APIs. (which is the SHA256 of protobuf-serialized data)

```py
self.txid = sign_weight["transaction"]["transaction"]["txID"]
```

To build a transaction without a network, you also need to provide the 'ref_block' in `TransactionBuilder.build()`.

**Comment by MioYvo** [comment]
I got it, it's very clever.
I mean this PR support building a Transaction from an **exists** `tx_json` which generated by `Transaction.to_json()` without network, user scenario like:

```python
def sign_tx_from_tx_json(tx_json: str):
    data = json.loads(tx_json)
    tx = Transaction(
        raw_data=data['raw_data'], 
        client=Tron(), 
        method=Some.contract.functions.Func, 
        sign_weight=data['sign_weight']
    )	# without network
    # locally use
    tx.sign(....)
	....
```

I see the `TransactionBuilder` class is made to build a `Transaction`.

Maybe a *classmethod* `TransactionBuilder.load_from_tx_json` is better? like:

```python
def sign_tx_from_tx_json(tx_json: str):
    data = json.loads(tx_json)	# {"txID":, "raw_data":, "signature":, "sign_weight"}
    tx_builder: TransactionBuilder = TransactionBuilder.load_from_tx_json(
        tx_json=data,
        client=Tron(), 
        method=Some.contract.functions.Func,
    )	# pass tx_json to TransactionBuilder, include "raw_data", "signature" and "sign_weight"
    tx: Transaction = tx_builder.build(
        ref_block_id=False, 	# str(provide a ref_block_id to build raw_data)
        			# False(not get ref_block_id, leave tx_builder.raw_data as it is)
        			# None(default, get ref_block_id from network to build raw_data)
    )	# build tx using signature and sign_weight if exists
    # locally use
    tx.sign(....)
```

**Comment by andelf** [comment]
Got it. I have the following ideas.

- Without a network, `ref_block`, `txID` will be empty
- Also the transaction might be outdated if it is expired (maximum `expiration` is 1 day)

- Add `to_json`, `from_json` to `Transaction`
- Add `update_ref_block` to `Transaction`, this will change the txID, and remove all signatures.

**Comment by andelf** [comment]
HOLD this. until a better idea comes.

**Comment by MioYvo** [comment]
Knock Knock

**Comment by MioYvo** [comment]
Code updated ~.~ 

* add `from_json` to `Transaction`
* add `update` to `Transaction`
* add property `is_expired` to `Transaction`, assert not expired when `sign()`
* add tests: sign_offline, transaction_update

**Comment by MioYvo** [comment]
@andelf

**Comment by andelf** [comment]
Sorry for reviewing too late.

will publish the next version soon.

**Pull request merged**
