### PR TITLE
added hd account feature as implemented in web3

### PR DESCRIPTION
**Pull request by jake-ephraim**

### CODE REVIEW

**Comment by jake-ephraim** [comment]
Added the hierarchical-deterministic (HD) wallet feature as implemented in the python package `web3`. some source code template were gotten from `https://github.com/trezor/python-mnemonic` and `https://github.com/ethereum/web3.py` and modified to integrate without additional dependencies.

**Comment by MrNaif2018** [comment]
Hi! Thank you for your PR.

I don't think that vendoring mnemonic package makes sense. What about making it an optional dependency instead?

**Comment by jake-ephraim** [comment]
okay, do you mean i should create a new git repo for it and add it as an extra_require in the setup?

**Comment by MrNaif2018** [comment]
Why a new git repo, if it's accessible as `mnemonic` package on PyPI? We can just add it in extra_require and make code work conditionally based on presence of such library

**Comment by jake-ephraim** [comment]
The package is not accessible from PyPi because i built it as part of the tronpy package. Unless you want me to build it separately as a standalone package that can then be pushed to PyPi independently.

**Comment by jake-ephraim** [comment]
Only the packages currently present are used to implement the code. There are no additional imports.

**Comment by jake-ephraim** [comment]
Alright, I will do that commit the change.

**Pull request closed without merging**
