### PR TITLE
Seperated `trigger_constant_contract` from `trigger_const_smart_contract_function` method

### PR DESCRIPTION
**Pull request by jake-ephraim**
needed the full dict returned by "wallet/triggerconstantcontract"

### CODE REVIEW

**Comment by MrNaif2018** [comment]
Hi! Why do we need another method if it just returns a fixed path of a different one? Just call the original method and access needed data at path

**Comment by jake-ephraim** [comment]
The original method filters out some important parameters such as `energy_used` and `energy_penalty` and only returns the `constant_result` parameter.

**Comment by jake-ephraim** [comment]
But it appears the original method  returning the `constant_result` is used, so i had to create another function to first return the complete data then the original function to parse out only the `constant_result` so that there is no breakage in the code.

**Comment by MrNaif2018** [comment]
Ah sorry, I've misread the diff. Thanks for the explanation
Hint: you can rebase your branch to avoid all those commits stacked together when you submit changes

**Review by MrNaif2018 — APPROVED** [review]
Thank you for your PR! Merging!

**Comment by jake-ephraim** [comment]
okay, thank you.

**Pull request merged**
